#!/usr/bin/env python3
"""
Turns `nm` output of the native code into armc_offsets.h: the offset of
every Df* entry point inside the armc resource (linked at address 0).
"""
import sys

symbols = {}
for line in sys.stdin:
    fields = line.split()
    if len(fields) == 3 and fields[1] in ("T", "t") and fields[2].startswith("Df"):
        symbols[fields[2]] = int(fields[0], 16)

required = ["DfInstall", "DfConfig", "DfSecondsToDateTime", "DfDayOfWeek",
            "DfDayOfMonth", "DfDateToAscii", "DfDateToDOWDMFormat",
            "DfDateTemplateToAscii", "DfSelectDayNative", "DfStrIToA"]
missing = [s for s in required if s not in symbols]
if missing:
    sys.exit("missing symbols: " + ", ".join(missing))
for name, offset in symbols.items():
    if offset & 3:
        sys.exit(f"{name} is not word aligned ({offset:#x})")

print("/* generated by tools/gen_offsets.py - do not edit */")
print("#ifndef ARMC_OFFSETS_H")
print("#define ARMC_OFFSETS_H")
for name in required:
    print(f"#define OFS_{name:<24} 0x{symbols[name]:04X}UL")
# the table follows `adr r0, 1f; bx lr` in DfConfig
print(f"#define OFS_CONFIG                   0x{symbols['DfConfig'] + 8:04X}UL")
print("#endif")
